package parqueadero;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author cymaniatico
 */
public class FrmParqueadero extends javax.swing.JFrame {

    /**
     * Creates new form FrmParqueadero
     */
    ArrayList<Parqueadero> listaParqueadero;
    String placa;
    String tiposVehiculos[]={"Carro", "Moto", "Bicicleta"};

    public FrmParqueadero() {
        initComponents();
        listaParqueadero = new ArrayList();
        txtPlaca.setText("");
        llenarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        btnRegistrarIngreso = new javax.swing.JButton();
        btnIngresarSalida = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRegistros = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        comboTipoVehiculo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ingrese la placa");

        txtPlaca.setText("jTextField1");

        btnRegistrarIngreso.setText("Registrar Ingreso");
        btnRegistrarIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarIngresoActionPerformed(evt);
            }
        });

        btnIngresarSalida.setText("Registrar Salida");
        btnIngresarSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarSalidaActionPerformed(evt);
            }
        });

        tableRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableRegistros);

        jLabel2.setText("Seleccione tipo de vehiculo");

        comboTipoVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPlaca))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboTipoVehiculo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegistrarIngreso)
                        .addGap(18, 18, 18)
                        .addComponent(btnIngresarSalida)
                        .addGap(0, 46, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrarIngreso)
                    .addComponent(btnIngresarSalida)
                    .addComponent(comboTipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarIngresoActionPerformed
        // TODO add your handling code here:
        if (!txtPlaca.getText().isEmpty() && comboTipoVehiculo.getSelectedIndex()>0) {
            placa = txtPlaca.getText().toUpperCase();
            if (listaParqueadero.isEmpty()) {
                listaParqueadero.add(new Parqueadero(placa, 
                        tiposVehiculos[comboTipoVehiculo.getSelectedIndex()-1]));
                JOptionPane.showMessageDialog(rootPane, "Ingreso realizado");
                mostrarInfo();
            } else {
                int pos = -1;
                for (int i = 0; i < listaParqueadero.size(); i++) {
                    if (listaParqueadero.get(i).getPlaca().equals(placa)
                            && listaParqueadero.get(i).getHoraSalida().equals("Dentro del Parqueadero")) {
                        pos = i;
                    }
                }
                if (pos == -1) {
                    listaParqueadero.add(new Parqueadero(placa,
                        tiposVehiculos[comboTipoVehiculo.getSelectedIndex()-1]));
                    JOptionPane.showMessageDialog(rootPane, "Ingreso realizado");
                    mostrarInfo();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "El vehiculo ya se encuentra dentro del parqueadero");

                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Faltan campos por diligenciar");

        }

    }//GEN-LAST:event_btnRegistrarIngresoActionPerformed

    private void btnIngresarSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarSalidaActionPerformed
        // TODO add your handling code here:
        if (!txtPlaca.getText().isEmpty()){
            placa = txtPlaca.getText().toUpperCase();
            int pos=-1;
            for(int i=0;i<listaParqueadero.size();i++){
                if(listaParqueadero.get(i).getPlaca().equals(placa)
                        && listaParqueadero.get(i).validarSalida() == null){
                    pos=i;
                    break;
                }
            }
            if(pos != -1){
                listaParqueadero.get(pos).setHoraSalida();
                JOptionPane.showMessageDialog(rootPane, "Salida registrada");
                mostrarInfo();
            }else{
                JOptionPane.showMessageDialog(rootPane, "Vehiculo no encontrado");
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Faltan campos por diligenciar");
        }
    }//GEN-LAST:event_btnIngresarSalidaActionPerformed

    public void mostrarInfo(){
        DefaultTableModel modelo = new DefaultTableModel();
        String encabezado[]={"Placa","Tipo de Vehiculo", "Hora de entrada", "Hora de salida"};
        modelo.setColumnIdentifiers(encabezado);
        for(int i=0;i<listaParqueadero.size();i++){
            modelo.addRow(new Object[]{listaParqueadero.get(i).getPlaca(),
                listaParqueadero.get(i).getTipoVehiculo(),
            listaParqueadero.get(i).getHoraEntrada(),
            listaParqueadero.get(i).getHoraSalida()});
        }
        tableRegistros.setModel(modelo);
    }
    
    public void llenarCombo(){
        comboTipoVehiculo.removeAllItems();
        comboTipoVehiculo.addItem("Seleccione...");
        for (int i = 0; i < tiposVehiculos.length; i++) {
            comboTipoVehiculo.addItem(tiposVehiculos[i]);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmParqueadero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmParqueadero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmParqueadero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmParqueadero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmParqueadero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresarSalida;
    private javax.swing.JButton btnRegistrarIngreso;
    private javax.swing.JComboBox<String> comboTipoVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableRegistros;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
